AWSTemplateFormatVersion: 2010-09-09
Description: Basic S3 CloudFormation Template
Resources:
  S3BucketForContent:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
Outputs:
  BucketName:
    Value: !Ref S3BucketForContent
    Description: Name of S3 Bucket Created